### ISSUE TITLE
can it compile to 64bit dll? 

### ISSUE THREAD

**Issue by DefinitlyEvil** [plushmonkey/mclib#16]
Hello there, 
  thank you for creating such cool tool, I retargeted the project to compile for 64bit arch and I also self-compiled all the dependencies. Although the compilation succeeded and also can it connect to servers, but when I delete the pointers I created, weird errors happened. 
I also retargeted to Windows 10.x API as VS2017 suggested. 
```cpp
delete this->dispatcher;
delete this->mc_client;
```
```
 	ntdll.dll!RtlReportCriticalFailure()	Unknown
 	ntdll.dll!RtlpHeapHandleError()	Unknown
 	ntdll.dll!RtlpHpHeapHandleError()	Unknown
 	ntdll.dll!RtlpLogHeapFailure()	Unknown
 	ntdll.dll!RtlFreeHeap()	Unknown
 	ucrtbase.dll!00007ffcab75d92b()	Unknown
 	mclib.dll!mc::core::Client::`vector deleting destructor'(unsigned int)	C++
>	Craft.dll!MCClient::Stop() Line 34	C++
 	[External Code]	
```
Google said it might be a heap corruption. 
Should I switch back to 32-bit or it was caused by my code?

**Comment by plushmonkey** [comment]
I've never actually compiled it with 64-bit target, so I'm not sure if it works. I see that you're deleting the dispatcher before the client, so that could be the problem. A lot of the members of client have to unregister handlers in each of their destructors, so deleting the dispatcher first would definitely mess that up.

I'll try to compile it in 64-bit myself sometime when I have some free time to see if there's any issues.

**Comment by DefinitlyEvil** [comment]
ok thx soooo much! :D 
I also tried not to delete dispatcher, the error also happened.

**Comment by plushmonkey** [comment]
Yeah, it works absolutely fine as a 64-bit build. I tested it with the example client and with my larger Terracotta project.

I don't have Windows 10 to test if something goes wrong with retargeting the build. I'd say the best way to build it would be to use CMake to generate a 64-bit build instead of using the supplied solution.

If that doesn't change anything, then it's most likely an issue with your object destruction order.

**Comment by DefinitlyEvil** [comment]
okay thanks! 
I'm gonna try to rebuild it. ;) 
I think my project configuration might be wrong.
